djcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name= 'logout'),
    path('register/', views.register_user, name= 'register'),
    path('record/<int:pk>', views.customer_record, name='record'),
    path('delete/<int:pk>', views.delete_record, name='delete'),
    path('add/', views.add_record, name='add'),
    path('update/<int:pk>', views.update, name='update'),
]

web/models.py
from django.db import models
from django.utils import timezone

class Record(models.Model):
    date_created = models.DateTimeField(auto_now_add = True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=20)

    def __str__(self):
        return(f"{self.first_name}  {self.last_name} {self.email}")
    

web/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from . form import SignUpForm
from .models import Record
from .form import AddRecord

def index(request):
    records = Record.objects.all()

    #checking if the user is logged in
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        #authenticate the user
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Login successfully')
            return redirect('web:index')
        else:
            messages.success(request, 'Incorrect username or password, please try again')
            return redirect('web:index')

    else:
        return render(request, 'web/index.html',{'records': records})


def user_login(request):
    pass


def user_logout(request):
    logout(request)
    messages.success(request, " You've been logged out!")
    return redirect('web:index')

def register_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # authenticate user
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request, user)
            messages.success(request, 'Regitration successful..')
            return redirect('web:index')
    else:
        form = SignUpForm()   
        return render(request, 'web/register.html', {'form':form})

    return render(request, 'web/register.html', {'form':form})

# Single customer information
def customer_record(request, pk):
    if request.user.is_authenticated:
        cust_record = Record.objects.get(id=pk)
        return render(request, 'web/record.html', {'cust_record':cust_record})
    else:
        messages.success(request, 'Kindly login to view this information!')
        return redirect('web:index')

# deleting a signle record
def delete_record(request, pk):
    if request.user.is_authenticated:
        del_record = Record.objects.get(id=pk)
        del_record.delete()
        messages.success(request, 'Record has been successfully deleted')
        return redirect('web:index')
    else:
        messages.success(request, 'You must be logged in to delete this record.')
        return redirect('web:index')
    

# Add record
def add_record(request):
    form = AddRecord(request.POST or None)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form.save()
            messages.success(request, 'Record has be added')
            return redirect('web:index')
        return render(request, 'web/add.html', {'form':form})
    else:
        messages.success(request, 'YOu must be logged in')
        return redirect('web:index')

# update user record 
def update(request, pk):
    if request.user.is_authenticated:
       current_record = Record.objects.get(id=pk)
       form = AddRecord(request.POST or None, instance=current_record)
       if form.is_valid():
            form.save()
            messages.success(request, 'Update successfully')
            return redirect('web:index')
       return render(request, 'web/update.html', {'form':form})
    else:
        messages.success(request, 'You must be logged in..')
        return redirect('web:login')

web/templates/web/add.html
{% extends "web/base.html" %}

{% block content %}
<div class="col-md-6 offset-md-3">
<h3 class="text-secondary">Add Customer</h3>

<form method="POST" action="{% url 'web:add' %}">
    {% csrf_token %}
    <form>
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Submit</button>
        <a href="{% url 'web:index' %}" class="btn btn-primary">Back</a>
    </form>
</div>
{% endblock content %}

web/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>crm - app</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Bootstrap -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'web/nav.html' %}
    <br/>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% if messages %}
                {% for message in messages  %}
                <div class="alert alert-dark alert-dismissible fade show" role="alert">
                    <strong class="text-success">{{message}}</strong> 
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                  </div>
                {% endfor %}
        
            {% endif %}
            </div>
        </div>
        
        {%block content%}

        {%endblock%}
    
    </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Bootstrap -->
</body>
</html>

web/templates/web/index.html
{%extends 'web/base.html'%} {%block content %} {% if user.is_authenticated %}
<h3>Customer Records</h3>

<table
  class="table table-striped text-secondary table-bordered border-secondary table-hover"
>
  <thead class="table-secondary">
    <tr>
      <th scope="col" class="text-primary">Sn</th>
      <th scope="col" class="text-primary">Full name</th>
      <th scope="col" class="text-primary">Email address</th>
      <th scope="col" class="text-primary">Phone</th>
      <th scope="col" class="text-primary">Address</th>
      <th scope="col" class="text-primary">City</th>
      <th scope="col" class="text-primary">State</th>
      <th scope="col" class="text-primary">Zip_Code</th>
      <th scope="col" class="text-primary">Date_Created</th>
    </tr>
  </thead>
  <tbody>
    {% if records %} {%for record in records %}
    <tr>
      <td><a href="{% url 'web:record' record.id %}">{{record.id}} </a></td>
      <td>{{record.first_name}} {{record.last_name}}</td>
      <td>{{record.email}}</td>
      <td>{{record.phone}}</td>
      <td>{{record.address}}</td>
      <td>{{record.city}}</td>
      <td>{{record.state}}</td>
      <td>{{record.zipcode}}</td>
      <td>{{record.date_created}}</td>
    </tr>
    {% endfor %} {%endif%}
  </tbody>
</table>

{%else%}

<div class="row mx-auto" style="width:100%" >

<div class="col-md-6 offset-md-3">

  <h2 class="text-center text-secondary">Login</h2>
<form method="POST" action="{% url 'web:index' %}">
  {% csrf_token %}
  <form>
    <div class="mb-3 mt-4">
      <input
        type="text"
        class="form-control"
        name="username"
        placeholder="Username"
        required
      />
    </div>
    <div class="mb-3">
      <input
        type="password"
        class="form-control"
        name="password"
        placeholder="Password"
        required
      />
    </div>
    <button type="submit" class="btn btn-success" style="width: 100%;">Submit</button>
  </form>

</div>
</div>


  {%endif%} {%endblock%}
</form>

web/templates/web/nav.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{%url 'web:index'%}">ROVERT CRM</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"aria-current="page" href="{% url 'web:index'%}"
            >Home</a
          >
        </li>

        {% comment %} User logout {% endcomment %} 
        
        {% if user.is_authenticated  %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:add' %}">Add Record</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:index' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'web:register' %}">Register</a>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<hr />

web/templates/web/record.html
{%extends 'web/base.html'%} {%block content %}

<div class="card">
  <div class="card-header text-white bg-secondary">
    {{ cust_record.first_name}} {{cust_record.last_name}}
  </div>
  <div class="card-body">
    <p><strong>Email:</strong> {{cust_record.email}}</p>
    <p><strong>Phone Number:</strong> {{cust_record.phone}}</p>
    <p><strong>Address:</strong> {{cust_record.address}}</p>
    <p><strong>City:</strong> {{cust_record.city}}</p>
    <p><strong>State:</strong> {{cust_record.state}}</p>
    <p><strong>Zidcode:</strong> {{cust_record.zipcode}}</p>
  </div>
</div>
<a href="{% url 'web:update' cust_record.id %}" class="btn mt-2 btn-primary"
  >Update</a
>
<a href="{% url 'web:delete' cust_record.id %}" class="btn mt-2 btn-danger"
  >Delete</a
>
{%endblock%}

web/templates/web/register.html
{% extends "web/base.html" %} {% block content %}
<div class="col-md-6 offset-md-3 p-4 mb-3 rounded-2 border">
  <h3 class="text-success text-center pb-2">Register User</h3>

  <form class="mb-4" method="POST">
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      Your form has errors! {% for field in form %} {% if field.errors %}
      {{field.errors}} {%endif%} {%endfor%}
      <strong class="text-success">{{field}}</strong>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {%endif%} {{form.as_p}}
    <button type="submit" class="btn btn-success">Register</button>
  </form>
</div>

{% endblock content %}

web/templates/web/update.html
{% extends "web/base.html" %} {% block content %}
<div class="col-md-6 offset-md-3">
  <h3>Update Record</h3>

  <form method="POST">
    {% csrf_token %}
    
    <form> {{form.as_p}}
    <button type="submit" class="btn btn-success">Update</button>
    <a href="{% url 'web:index' %}" class="btn btn-primary">Back</a> 
  </form>
</div>
{% endblock content %}